config/routes.rb
Spree::Core::Engine.routes.draw do
	# Add your extension routes here
	namespace :admin do
		resources :suppliers do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end
	end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
	has_one :supplier
  
  private

  def product_params
    params.require(:product).permit(:supplier_id)
  end
end

app/models/spree/supplier.rb
module Spree
	class Supplier < ActiveRecord::Base
		belongs_to :product, :class_name => 'Spree::Product'
		validates :supplier_name, presence: true

		private
  	def supplier_params
    	params.require(:supplier).permit(:supplier_name)
  	end
	end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  before_filter :load_supplier_data

  private
  def load_supplier_data
  	@suppliers = Spree::Supplier.all
  end
end

app/controllers/spree/admin/suppliers_controller.rb
class Spree::Admin::SuppliersController < Spree::Admin::ResourceController
	before_filter :load_data
	
	def update_values_positions
		params[:positions].each do |id, index|
      OptionValue.where(:id => id).update_all(:position => index)
    end
	end

	private
	def load_data
		@suppliers = Spree::Supplier.all			
	end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  before_filter :load_supplier_data

  private
  def load_supplier_data
  	@suppliers = Spree::Supplier.all
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/spree/admin/suppliers/_form.html.erb
<div data-hook="admin_seller_form_fields" class="align-center row">
  <div class="alpha eight columns">
    <%= f.field_container :supplier_name do %>
      <%= f.label :supplier_name, Spree.t(:supplier_name) %> <span class="required">*</span><br />
      <%= f.text_field :supplier_name, :class => "fullwidth" %>
      <%= f.error_message_on :supplier_name %>
    <% end %>
  </div>
</div>

app/views/spree/admin/suppliers/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_supplier) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_suppliers_list), spree.admin_suppliers_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @supplier } %>

<%= form_for [:admin, @supplier] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

<% if @suppliers.any? %>
<table class="index sortable" id="listing_suppliers">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 65%">
    <col style="width: 25%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr class="spree_supplier <%= cycle('odd', 'even')%>" id="<%= spree_dom_id supplier %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= supplier.supplier_name %></td>
        <td class="actions">
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:supplier)) %>,
    <%= link_to Spree.t(:add_one), new_admin_supplier_path %>!
  </div>
<% end %>

app/views/spree/admin/suppliers/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:suppliers) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_supplier_link">
    <%= button_link_to Spree.t(:new_supplier), new_admin_supplier_url, { :remote => true, :icon => 'icon-plus', :id => 'new_supplier_link' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<div id="new_supplier"></div>

<% if @suppliers.any? %>
<table class="index sortable" id="listing_suppliers">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 55%">
    <col style="width: 35%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr class="spree_supplier <%= cycle('odd', 'even')%>" id="<%= spree_dom_id supplier %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= supplier.supplier_name %></td>
        <td class="actions">
          <%= link_to_edit(supplier, :class => 'admin_edit_supplier', :no_text => true) %>
          <%= link_to_delete(supplier, :no_text => true) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:supplier)) %>,
    <%= link_to Spree.t(:add_one), new_admin_supplier_path %>!
  </div>
<% end %>

app/views/spree/admin/suppliers/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @supplier } %>

<%= form_for [:admin, @supplier] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:new_supplier) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/suppliers/new.js.erb
$("#new_supplier").html('<%= escape_javascript(render :template => "spree/admin/suppliers/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_supplier_link").parent().hide();